### ISSUE TITLE
Multiple Maintainers Needed

### ISSUE THREAD

**Issue by PhilETaylor** [php-earth/alpine#17]
This project needs multiple maintainers to be a success.

Waiting weeks for releases of security releases is not acceptable. I appreciate its a side project but for this project to be a success it needs to have multiple maintainers so that builds can be made in the absence of volunteer help.

As the build instructions are incomplete, and in a previous ticket you alluded to the fact that dedicated hardware/environment was needed, maybe we could encourage you to document all that and open this project (which my business and I guess others depend on). :-)

**Comment by petk** [comment]
Hello, thanks for reporting issues and volunteering your time... Proper way here is actually to improve upstream libraries and Alpine packages.

> Waiting weeks for releases of security releases is not acceptable

What is acceptable and not acceptable is within the limits of time and energy that is dedicated to this project and what actually is a security release.

Thanks for your time and effort to contribute the way you can... I'll see if making a more detailed documentation for this is an option. Otherwise the most proper way is actually to update and fix (if there is anything missing) the Alpine Wiki pages: https://wiki.alpinelinux.org/wiki/Main_Page
